### ISSUE TITLE
[STH] error when try to start the app, but it is running in the same port 

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/IoT-STH#25]
Is neccesary the exception message? I recommend use a message more especific to the error.

Error returned:
```
net.js:1236
    throw new Error('Not running');
          ^
Error: Not running
    at Server.close (net.js:1236:11)
    at internals.Connection._stop (/home/sysadmin/git/IoT-STH/node_modules/hapi/lib/connection.js:188:19)
    at /home/sysadmin/git/IoT-STH/node_modules/hapi/lib/server.js:210:20
    at iterate (/home/sysadmin/git/IoT-STH/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/home/sysadmin/git/IoT-STH/node_modules/hapi/node_modules/items/lib/index.js:38:9)
    at internals.Server.stop (/home/sysadmin/git/IoT-STH/node_modules/hapi/lib/server.js:208:11)
    at Object.stopServer (/home/sysadmin/git/IoT-STH/src/sth_server.js:163:14)
    at exitGracefully (/home/sysadmin/git/IoT-STH/src/sth_app.js:45:15)
    at process.module.exports.startup (/home/sysadmin/git/IoT-STH/src/sth_app.js:114:12)
    at process.emit (events.js:95:17)
npm ERR! weird error 7
npm ERR! not ok code 0

```

**Comment by iariasleon** [comment]
LGTM
```

> fiware-sth-rest-api@0.1.0 start /home/sysadmin/git/IoT-STH
> node ./src/sth_app

time=2015-04-22T13:35:57.214Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_DB_CONN_OPEN | msg=Connection to MongoDB mongodb://@localhost:27017/orion successfully established
time=2015-04-22T13:35:57.255Z | lvl=FATAL | corr=NA | trans=NA | op=OPER_STH_SHUTDOWN | msg=Error: listen EADDRINUSE (another STH instance maybe already listening on the same port), alarm_status=ALARM
time=2015-04-22T13:35:57.255Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_SERVER_STOP | msg=Stopping the STH server...
time=2015-04-22T13:35:57.255Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_SERVER_STOP | msg=No hapi server running
time=2015-04-22T13:35:57.256Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_DB_CONN_CLOSE | msg=Closing the connection to the database...
time=2015-04-22T13:35:57.261Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_DB_CONN_CLOSE | msg=Connection to MongoDb succesfully closed
npm ERR! weird error 1
npm ERR! not ok code 0

```
